# Ultralytics YOLO ğŸš€, AGPL-3.0 license

[package]
name = "YOLO_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
image = { version = "0.24.7", default-features = false, features = ["jpeg", "png", "webp-encoder"] }
imageproc = { version = "0.23.0", default-features = false }
ndarray = { version = "0.15.6" }
ort = { version = "1.16.3", default-features = false, features = ["load-dynamic", "copy-dylibs", "half"] }
rusttype = { version = "0.9", default-features = false }
anyhow = { version = "1.0.75" }
regex = { version = "1.5.4" }
rand = { version = "0.8.5" }
chrono = { version = "0.4.30" }
half = { version = "2.3.1" }
dirs = { version = "5.0.1" }
ureq = { version = "2.9.1" }

win-screenshot = { path = "win-screenshot-main" } #æˆªå±
libloading = "0.8.4"#è°ƒç”¨åŠ¨æ€åº“
thiserror = "1.0.61"
minifb = "0.27.0"#è½»é‡çº§uiçª—å£debugç”¨
device_query = "2.1.0" #ç®€å•é¼ æ ‡å’Œé”®ç›˜ç›‘å¬
paddleocr = { path = "paddleocr" }

[lib]
name = "lib"
path = "src/lib.rs"

[[example]]
name = "key_mouse"

